var STORMPATH_API_KEY = exports.STORMPATH_API_KEY = "KSGFP997ET5F8V6NXW6YL67MX"
var STORMPATH_API_SECRET_KEY = exports .STORMPATH_API_SECRET_KEY= "ij4tDJOY1fR/QYcacY/1Iy6zW+0A+OQI3XzVCFcX6OE"

module.exports = exports
